name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Protobuf compiler
      run: sudo apt install -y protobuf-compiler
    - name: Submodules init
      run: git submodule update --init
    - name: Check
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
